version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: infra/docker/api.Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - postgres
      - mongo
      - redis
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meridian
    ports:
      - "5432:5432"
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
